<?php
    return array(
        'category/filter/([a-z]+)/(.+)/(.+)' => 'category/filter/$1/$2/$3',
        'category/filterajax/([a-z]+)/(.+)/(.+)' => 'category/filterajax/$1/$2/$3',
        'category/viewajax/([a-z]+)' => 'category/viewajax/$1',
        'category/([a-z]+)' => 'category/view/$1',
        'product/rate/([0-9]+)/([0-9]+)' => 'product/rate/$1/$2',
        'product/rateajax/([0-9]+)/([0-9]+)' => 'product/rateajax/$1/$2',
        'product/viewajax/([0-9]+)' => 'product/viewajax/$1',
        'product/([0-9]+)' => 'product/view/$1',
        'search' => 'product/search',
        'category' => 'products/view',
        '' => 'category/view',
        'login' => 'user/login',
        'logout' => 'user/logout',
        'feedback' => 'user/feedback',
        'registration' => 'user/registration',
        'messages/([0-9]+)' => 'messages/view/$1',
        'messages/([0-9]+)/asc' => 'messages/view/$1/asc',
        'messages/([0-9]+)/desc' => 'messages/view/$1/desc',
        'messages/deleteall' => 'messages/deleteAll',
        'messages/delete/([0-9]+)' => 'messages/delete/$1',
        'messages/reply/([0-9]+)' => 'messages/reply/$1',
        'messages' => 'messages/view',
        'cart/addajax/([0-9]+)' => 'cart/addajax/$1',
        'cart/add/([0-9]+)' => 'cart/add/$1',
        'cart/delete/([0-9]+)' => 'cart/delete/$1',
        'cart/deleteajax/([0-9]+)' => 'cart/deleteajax/$1',
        'rss/([0-9]+)' => 'rss/item/$1',
        'rss' => 'rss/view',
        'admin/addImage' => 'admin/addImage',
        'admin/view' => 'admin/view'
    );